{
    'name': 'ProSys Purchase Requisition',
    'version': '16.0.1.0.1',
    'category': 'Purchases',
    'summary': 'ProSys Purchase Requisition',
    'description': 'ProSys Purchase Requisition',
    'author': 'ProSys Technology',
    'company': 'ProSys Technology',
    'maintainer': 'ProSys Technology',
    'images': ['static/description/banner.png'],
    'website': 'https://www.prosys-sa.com',
    'depends': ['base', 'hr', 'stock', 'purchase'],
    'data': [
        'security/security_access.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'views/purchase_requisition.xml',
        'views/purchase_plan_view.xml',
        'views/menu.xml',
        'views/hr_work_location_view.xml',
        'views/purchase_order_view.xml',
        'views/stock_picking_view.xml',
        'views/action_print_requisition.xml',
        'report/purchase_requisition_template.xml',
        'report/purchase_requisition_report.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
